spring:
  application:
    name: ai-calendar
  datasource:
    url: jdbc:mysql://localhost:3306/ai_calendar?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
