spring:
  application:
    name: ai-calendar
  datasource:
    url: jdbc:h2:file:/tmp/db;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
